'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class PerguntasRespostas
    Inherits DataSet
    
    Private tablePerguntasRespostas As PerguntasRespostasDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("PerguntasRespostas")) Is Nothing) Then
                Me.Tables.Add(New PerguntasRespostasDataTable(ds.Tables("PerguntasRespostas")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property PerguntasRespostas As PerguntasRespostasDataTable
        Get
            Return Me.tablePerguntasRespostas
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As PerguntasRespostas = CType(MyBase.Clone,PerguntasRespostas)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("PerguntasRespostas")) Is Nothing) Then
            Me.Tables.Add(New PerguntasRespostasDataTable(ds.Tables("PerguntasRespostas")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tablePerguntasRespostas = CType(Me.Tables("PerguntasRespostas"),PerguntasRespostasDataTable)
        If (Not (Me.tablePerguntasRespostas) Is Nothing) Then
            Me.tablePerguntasRespostas.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "PerguntasRespostas"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/PerguntasRespostas.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tablePerguntasRespostas = New PerguntasRespostasDataTable
        Me.Tables.Add(Me.tablePerguntasRespostas)
    End Sub
    
    Private Function ShouldSerializePerguntasRespostas() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub PerguntasRespostasRowChangeEventHandler(ByVal sender As Object, ByVal e As PerguntasRespostasRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class PerguntasRespostasDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnDESPGN As DataColumn
        
        Private columnDESRSP As DataColumn
        
        Friend Sub New()
            MyBase.New("PerguntasRespostas")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property DESPGNColumn As DataColumn
            Get
                Return Me.columnDESPGN
            End Get
        End Property
        
        Friend ReadOnly Property DESRSPColumn As DataColumn
            Get
                Return Me.columnDESRSP
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As PerguntasRespostasRow
            Get
                Return CType(Me.Rows(index),PerguntasRespostasRow)
            End Get
        End Property
        
        Public Event PerguntasRespostasRowChanged As PerguntasRespostasRowChangeEventHandler
        
        Public Event PerguntasRespostasRowChanging As PerguntasRespostasRowChangeEventHandler
        
        Public Event PerguntasRespostasRowDeleted As PerguntasRespostasRowChangeEventHandler
        
        Public Event PerguntasRespostasRowDeleting As PerguntasRespostasRowChangeEventHandler
        
        Public Overloads Sub AddPerguntasRespostasRow(ByVal row As PerguntasRespostasRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddPerguntasRespostasRow(ByVal DESPGN As String, ByVal DESRSP As String) As PerguntasRespostasRow
            Dim rowPerguntasRespostasRow As PerguntasRespostasRow = CType(Me.NewRow,PerguntasRespostasRow)
            rowPerguntasRespostasRow.ItemArray = New Object() {DESPGN, DESRSP}
            Me.Rows.Add(rowPerguntasRespostasRow)
            Return rowPerguntasRespostasRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As PerguntasRespostasDataTable = CType(MyBase.Clone,PerguntasRespostasDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New PerguntasRespostasDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnDESPGN = Me.Columns("DESPGN")
            Me.columnDESRSP = Me.Columns("DESRSP")
        End Sub
        
        Private Sub InitClass()
            Me.columnDESPGN = New DataColumn("DESPGN", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESPGN)
            Me.columnDESRSP = New DataColumn("DESRSP", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESRSP)
        End Sub
        
        Public Function NewPerguntasRespostasRow() As PerguntasRespostasRow
            Return CType(Me.NewRow,PerguntasRespostasRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New PerguntasRespostasRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(PerguntasRespostasRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.PerguntasRespostasRowChangedEvent) Is Nothing) Then
                RaiseEvent PerguntasRespostasRowChanged(Me, New PerguntasRespostasRowChangeEvent(CType(e.Row,PerguntasRespostasRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.PerguntasRespostasRowChangingEvent) Is Nothing) Then
                RaiseEvent PerguntasRespostasRowChanging(Me, New PerguntasRespostasRowChangeEvent(CType(e.Row,PerguntasRespostasRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.PerguntasRespostasRowDeletedEvent) Is Nothing) Then
                RaiseEvent PerguntasRespostasRowDeleted(Me, New PerguntasRespostasRowChangeEvent(CType(e.Row,PerguntasRespostasRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.PerguntasRespostasRowDeletingEvent) Is Nothing) Then
                RaiseEvent PerguntasRespostasRowDeleting(Me, New PerguntasRespostasRowChangeEvent(CType(e.Row,PerguntasRespostasRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovePerguntasRespostasRow(ByVal row As PerguntasRespostasRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class PerguntasRespostasRow
        Inherits DataRow
        
        Private tablePerguntasRespostas As PerguntasRespostasDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tablePerguntasRespostas = CType(Me.Table,PerguntasRespostasDataTable)
        End Sub
        
        Public Property DESPGN As String
            Get
                Try 
                    Return CType(Me(Me.tablePerguntasRespostas.DESPGNColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePerguntasRespostas.DESPGNColumn) = value
            End Set
        End Property
        
        Public Property DESRSP As String
            Get
                Try 
                    Return CType(Me(Me.tablePerguntasRespostas.DESRSPColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePerguntasRespostas.DESRSPColumn) = value
            End Set
        End Property
        
        Public Function IsDESPGNNull() As Boolean
            Return Me.IsNull(Me.tablePerguntasRespostas.DESPGNColumn)
        End Function
        
        Public Sub SetDESPGNNull()
            Me(Me.tablePerguntasRespostas.DESPGNColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDESRSPNull() As Boolean
            Return Me.IsNull(Me.tablePerguntasRespostas.DESRSPColumn)
        End Function
        
        Public Sub SetDESRSPNull()
            Me(Me.tablePerguntasRespostas.DESRSPColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class PerguntasRespostasRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As PerguntasRespostasRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As PerguntasRespostasRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As PerguntasRespostasRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
