'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2502
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2502.
'
Namespace ServidorDiretorios
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServidorDiretoriosSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class ServidorDiretorios
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://framework2008prd.martins.com.br/Vendas.ServidorDiretorios/ServidorDiretori"& _ 
"os.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/criarUsuario", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function criarUsuario(ByVal nomeUsuario As String, ByVal senhaUsuario As String) As Boolean
            Dim results() As Object = Me.Invoke("criarUsuario", New Object() {nomeUsuario, senhaUsuario})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BegincriarUsuario(ByVal nomeUsuario As String, ByVal senhaUsuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("criarUsuario", New Object() {nomeUsuario, senhaUsuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndcriarUsuario(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluirUsuario", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function excluirUsuario(ByVal nomeUsuario As String) As Boolean
            Dim results() As Object = Me.Invoke("excluirUsuario", New Object() {nomeUsuario})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginexcluirUsuario(ByVal nomeUsuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("excluirUsuario", New Object() {nomeUsuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndexcluirUsuario(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarSenhaUsuario", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlterarSenhaUsuario(ByVal nomeUsuario As String, ByVal senhaUsuario As String) As Boolean
            Dim results() As Object = Me.Invoke("AlterarSenhaUsuario", New Object() {nomeUsuario, senhaUsuario})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginAlterarSenhaUsuario(ByVal nomeUsuario As String, ByVal senhaUsuario As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AlterarSenhaUsuario", New Object() {nomeUsuario, senhaUsuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAlterarSenhaUsuario(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
    End Class
End Namespace
