'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2494
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2494.
'
Namespace Email
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EmailSoap", [Namespace]:="http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email")>  _
    Public Class Email
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("VAK020.Email.Email")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/Martins.Web.Services.CorreioEletronico/Email.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email/EmailEnviar", RequestNamespace:="http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email", ResponseNamespace:="http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EmailEnviar(ByVal TipoMensagem As Decimal, ByVal Cabecalho As String, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal Enderecos() As EnderecoEmail, ByVal Corpo() As String, ByVal SistemaParaTratarDelegacao As String) As Integer
            Dim results() As Object = Me.Invoke("EmailEnviar", New Object() {TipoMensagem, Cabecalho, Enderecos, Corpo, SistemaParaTratarDelegacao})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginEmailEnviar(ByVal TipoMensagem As Decimal, ByVal Cabecalho As String, ByVal Enderecos() As EnderecoEmail, ByVal Corpo() As String, ByVal SistemaParaTratarDelegacao As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EmailEnviar", New Object() {TipoMensagem, Cabecalho, Enderecos, Corpo, SistemaParaTratarDelegacao}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEmailEnviar(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email/EmailEnviarAnexos"& _ 
"", RequestNamespace:="http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email", ResponseNamespace:="http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EmailEnviarAnexos(ByVal TipoMensagem As Decimal, ByVal Cabecalho As String, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal Enderecos() As EnderecoEmail, ByVal Corpo() As String, ByVal SistemaParaTratarDelegacao As String, ByVal Anexos() As String) As Integer
            Dim results() As Object = Me.Invoke("EmailEnviarAnexos", New Object() {TipoMensagem, Cabecalho, Enderecos, Corpo, SistemaParaTratarDelegacao, Anexos})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginEmailEnviarAnexos(ByVal TipoMensagem As Decimal, ByVal Cabecalho As String, ByVal Enderecos() As EnderecoEmail, ByVal Corpo() As String, ByVal SistemaParaTratarDelegacao As String, ByVal Anexos() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EmailEnviarAnexos", New Object() {TipoMensagem, Cabecalho, Enderecos, Corpo, SistemaParaTratarDelegacao, Anexos}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEmailEnviarAnexos(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email")>  _
    Public Class EnderecoEmail
        
        '<remarks/>
        Public Endereco As String
        
        '<remarks/>
        Public TipoEndereco As enmTipoEndereco
        
        '<remarks/>
        Public TipoEntidade As enmTipoEntidade
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email")>  _
    Public Enum enmTipoEndereco
        
        '<remarks/>
        Remetente
        
        '<remarks/>
        Destinatario
        
        '<remarks/>
        ComCopia
        
        '<remarks/>
        ComCopiaOculta
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Martins.Web.Services.CorreioEletronico/Email")>  _
    Public Enum enmTipoEntidade
        
        '<remarks/>
        Funcionario
        
        '<remarks/>
        Representante
        
        '<remarks/>
        GerenteMercado
        
        '<remarks/>
        Externo
    End Enum
End Namespace
